In [1]:
import numpy as np
from PIL import Image 
import glob

In [2]:
image_list =[]
resized_image=[]

In [3]:
def upload_images():
    try:
        for file_name in glob.glob('C:/Users/Hamza pc/*.jpg'):
            img=Image.open(file_name)
            image_list.append(img)
    except IOError:print ("Error: can\'t find file or read data")

In [4]:
def convert_img():
    try:
        for image in image_list:
            image=image.resize((200,200))
            resized_image.append(image)
    except ValueError as Argument:
        print ("The argument does not contain \n", Argument)

In [5]:
def Save_img():
    try :
        for (i,new) in enumerate(resized_image):
            new.save('{}{}{}'.format('C:/Users/Hamza pc/Desktop/photos/New_image',i+1,'.jpg'))
    except Exception as err:print("Erro {}".format(err))    
            

In [6]:
def img_to_array():
    try:
        for img1 in resized_image: 
            global new_image
            new_image =np.array(img1)
    except Exception as err:print("Erro {}".format(err))    

In [7]:
def main():
    upload_images()
    convert_img()
    Save_img()
    img_to_array()
    print("Shape of numpy Array = ",new_image.shape)
    print("Size of Numpy Array = ",new_image.size)
    print("Indices are given \n ",new_image[:,:,2])

In [10]:
if __name__=='__main__':
    main()

Shape of numpy Array =  (200, 200, 3)
Size of Numpy Array =  120000
Indices are given 
  [[255 255 255 ... 181 187 194]
 [255 255 255 ... 181 187 194]
 [255 255 255 ... 167 173 177]
 ...
 [ 36  36  35 ... 244 248 247]
 [ 36  36  35 ... 241 245 245]
 [ 36  36  35 ... 241 245 245]]
